#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define WINSOCK_ERROR_HEADER 0x0

#define CON2SERV_ERROR WINSOCK_ERROR_HEADER+1
#define CLOSECONN_ERROR WINSOCK_ERROR_HEADER+2
#define UPDATESERV_ERROR WINSOCK_ERROR_HEADER+3

#endif